name: django-cms-boilerplate
domain: example.dev

timezone: "Europe/Berlin"
secret_key: "django-secret-key"
# sentry_dsn: "sentry-dsn"

plugins:
  - teams
#  - components
#  - contact_form
#  - gallery
#  - cookies_banner

languages:
  - de
  - en

templates:
  home: "Custom Home Template"

user_settings:
  title: 'Website Title'
  name: 'Name or Company'
  email: 'Contact E-Mail'
#  address: 'Your Address'
#  zipcode: 'Your Zipcode'
#  city: 'Your City'
#  country: 'Your Country'
#  phone: 'Your Phone Number'
#  mobile: 'Your Mobile Number'
#  fax: 'Your Fax Number'
