version: '3.5'

networks:
  traefik:
    external: true

volumes:
  static:

services:
  cms:
    image: rehborn/djangocms-boilerplate:main
    volumes:
      - /srv/cms/config:/app/config/
      - /srv/cms/media:/app/media/
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.cms.rule=Host(`example.local`) && PathPrefix(`/`)
    depends_on:
      - postgres
      - redis

  static:
    image: nginx:latest
    volumes:
      - static:/usr/share/nginx/html/static/
      - /srv/cms/media:/usr/share/nginx/html/media/
    labels:
      - traefik.enable=true
      - traefik.http.routers.static.rule=Host(`example.local`) && PathPrefix(`/static/`)
      - traefik.http.routers.media.rule=Host(`example.local`) && PathPrefix(`/media/`)

  job-once:
    image: rehborn/djangocms-boilerplate:main
    command: >
      poetry run python /app/manage.py collectstatic --noinput && 
      poetry run python /app/manage.py boil
    volumes:
      - /srv/cms/config:/app/config
      - static:/app/static/
    depends_on:
      - postgres
      - redis
    restart: on-failure

  job-migrate:
    image: rehborn/djangocms-boilerplate:main
    command: poetry run python /app/manage.py migrate
    volumes:
      - /srv/cms/config:/app/config
    depends_on:
      - postgres
      - redis
    restart: 'no'

  postgres:
    image: postgres:12
    volumes:
    - /srv/cms/postgres/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always

  redis:
    image: redis:7
    restart: always
