# Generated by Django 4.2.5 on 2023-09-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
