# Generated by Django 4.2.5 on 2023-09-11 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='wird im Menü verwendet', max_length=30, verbose_name='Titel')),
                ('name', models.CharField(blank=True, max_length=60, verbose_name='Teamname')),
                ('name_de', models.CharField(blank=True, max_length=60, null=True, verbose_name='Teamname')),
                ('name_en', models.CharField(blank=True, max_length=60, null=True, verbose_name='Teamname')),
                ('slug', models.SlugField(blank=True, help_text='muss eindeutig sein, wird aus dem Titel generiert', unique=True)),
                ('description', models.TextField(blank=True, help_text='optional')),
                ('description_de', models.TextField(blank=True, help_text='optional', null=True)),
                ('description_en', models.TextField(blank=True, help_text='optional', null=True)),
                ('menu', models.BooleanField(default=False, verbose_name='collapse users in menu')),
                ('template', models.CharField(choices=[('team.html', 'Team')], default='team.html', max_length=30)),
                ('ordering', models.CharField(choices=[('name_asc', 'Name aufsteigend'), ('name_desc', 'Name absteigend'), ('prio_asc', 'Priorität aufsteigend'), ('prio_desc', 'Priorität absteigend')], default='asc', max_length=12)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='professional title')),
                ('title_de', models.CharField(blank=True, max_length=30, null=True, verbose_name='professional title')),
                ('title_en', models.CharField(blank=True, max_length=30, null=True, verbose_name='professional title')),
                ('role', models.CharField(blank=True, max_length=30, verbose_name='role')),
                ('role_de', models.CharField(blank=True, max_length=30, null=True, verbose_name='role')),
                ('role_en', models.CharField(blank=True, max_length=30, null=True, verbose_name='role')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True)),
                ('description_de', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True)),
                ('description_en', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0, help_text='Sortierungspriorität')),
                ('slug', models.SlugField(blank=True, help_text='muss eindeutig sein, wird durch Kombination von Vor- und Nachnamen generiert', unique=True)),
                ('background', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background', to=settings.FILER_IMAGE_MODEL)),
                ('photo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo', to=settings.FILER_IMAGE_MODEL)),
                ('team', models.ManyToManyField(blank=True, related_name='members', to='cms_teams.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(choices=[('email', 'email'), ('phone', 'Phone'), ('linkedin', 'Linkedin'), ('xing', 'XING'), ('link', 'Link'), ('other', 'Other')], max_length=16)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('value', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=0, help_text='Sortierungspriorität')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'info',
                'verbose_name_plural': 'infos',
            },
        ),
        migrations.CreateModel(
            name='TeamPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('template', models.CharField(choices=[('plugin_team.html', 'Team')], max_length=255)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms_teams.team')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='MemberPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('template', models.CharField(choices=[('plugin_member.html', 'Member')], max_length=255)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms_teams.userprofile')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
